// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDHB74MExQI5YDzR9oclrK_HHfW-LLvw4',
    appId: '1:46738584361:web:aa1d7c64ab8a5c49d67d38',
    messagingSenderId: '46738584361',
    projectId: 'final-submission-ml',
    authDomain: 'final-submission-ml.firebaseapp.com',
    storageBucket: 'final-submission-ml.firebasestorage.app',
    measurementId: 'G-TJ44MM138K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw5daENBCyuNKHeIEmQpSl1cjUgMUBeIg',
    appId: '1:46738584361:android:c8fe733cab06c24fd67d38',
    messagingSenderId: '46738584361',
    projectId: 'final-submission-ml',
    storageBucket: 'final-submission-ml.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHMlcHn41UYD1Cqa-14gum8dLtZuIZynw',
    appId: '1:46738584361:ios:29ce91d23e5d91ebd67d38',
    messagingSenderId: '46738584361',
    projectId: 'final-submission-ml',
    storageBucket: 'final-submission-ml.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHMlcHn41UYD1Cqa-14gum8dLtZuIZynw',
    appId: '1:46738584361:ios:29ce91d23e5d91ebd67d38',
    messagingSenderId: '46738584361',
    projectId: 'final-submission-ml',
    storageBucket: 'final-submission-ml.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDHB74MExQI5YDzR9oclrK_HHfW-LLvw4',
    appId: '1:46738584361:web:45b6fae7ed103c9ad67d38',
    messagingSenderId: '46738584361',
    projectId: 'final-submission-ml',
    authDomain: 'final-submission-ml.firebaseapp.com',
    storageBucket: 'final-submission-ml.firebasestorage.app',
    measurementId: 'G-3CYF19PLYR',
  );
}
